name: CI

on: workflow_dispatch

jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - name: Hello World
        run: |
          echo "Hello World"
